[config]
reload_apps = true

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua.template"
output_path = "~/.config/hypr/colors.lua"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.colors.json.template"
output_path = "~/.config/quickshell/colors.json"

[templates.alacritty]
input_path = "~/.config/matugen/templates/alacritty-colors.toml.template"
output_path = "~/.cache/matugen/colors.toml"

[templates.cava]
input_path = "~/.config/matugen/templates/cava-colors.ini.template"
output_path = "~/.config/cava/colors"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi.template'
output_path = '~/.config/rofi/colors.rasi'

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim-colors.lua.template"
output_path = "~/.config/nvim/matugen_colors.lua"