# Apps al iniciar sesión
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/libexec/xdg-desktop-portal-hyprland
exec-once = /usr/libexec/xdg-desktop-portal-gtk

# Wallpaper sobrio (wallust/swww si está disponible)
exec-once = sh -c 'sleep 1; [ -f ~/.config/hypr/wallpaper_effects/wallpaper.jpg ] && swww-daemon && swww img ~/.config/hypr/wallpaper_effects/wallpaper.jpg --transition-type fade'
