# Atajos personalizados — dev + fe
# Se fusionan con los de JaKooLit Hyprland-Dots

bind = $mainMod SHIFT, C, exec, cursor
bind = $mainMod SHIFT, B, exec, la-palabra-del-senor
bind = $mainMod SHIFT, Y, exec, biblia
bind = $mainMod SHIFT, P, exec, thunar ~/Projects
