hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon")
  hl.exec_cmd("quickshell")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("sh -c 'wl-paste --type text --watch cliphist store &'")
  hl.exec_cmd("sh -c 'wl-paste --type image --watch cliphist store &'")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user start xdg-desktop-portal")
  hl.exec_cmd("sh -c 'WALL=\"$HOME/.config/hypr/wallpapers/wallpaper.jpg\"; if [ -f \"$WALL\" ]; then matugen image \"$WALL\" 2>/dev/null || true; awww img \"$WALL\" --transition-type wave --transition-step 90 2>/dev/null || true; fi'")
end)
