general {
    lock_cmd = pgrep -x -f "quickshell -p $HOME/.config/quickshell/Lock.qml" || quickshell -p $HOME/.config/quickshell/Lock.qml
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn off display shortly after (so it locks first)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
