animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    animation = windows, 1, 4, easeOutQuint, slide
    animation = windowsOut, 1, 2, easeOutQuint, slide
    animation = border, 1, 4, easeOutQuint
    animation = fade, 1, 4, easeOutQuint
    animation = workspaces, 1, 3, easeOutQuint, slide
}
