$mainMod = SUPER

# Cerrar ventana: SUPER+Q, SUPER+W o Alt+F4
bind = $mainMod, Q, killactive
bind = $mainMod, W, killactive
bind = ALT, F4, killactive

# Flotar / pantalla completa
bind = $mainMod, T, togglefloating
bind = $mainMod, F, fullscreen

# Apps
bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, E, exec, ~/.config/ml4w/settings/filemanager.sh
bind = $mainMod CTRL, RETURN, exec, rofi -show drun
bind = $mainMod, B, exec, ~/.config/ml4w/settings/browser.sh
bind = $mainMod, J, layoutmsg, togglesplit
bind = $mainMod SHIFT, M, exit

# Audio / brillo
bind = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+
bind = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind = , XF86MonBrightnessUp, exec, brightnessctl set 10%+
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-
bind = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Navegar
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
