# Fe — La Palabra del Señor y Biblia
bind = $mainMod SHIFT, B, exec, la-palabra-del-senor
bind = $mainMod SHIFT, Y, exec, biblia

# Dev
bind = $mainMod SHIFT, C, exec, cursor
bind = $mainMod SHIFT, P, exec, thunar ~/Projects
