# Sobrio — estilo dev profesional
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(89b4faff)
    col.inactive_border = rgba(585b70aa)
    layout = dwindle
    resize_on_border = true
}
