# Window rules — minimal
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = center, class:^(pavucontrol)$
windowrule = center, class:^(nm-connection-editor)$
