# Hyprland 0.56+ — ventanas flotantes + look ML4W (vidrio)
windowrule = float on, center on, match:class ^(pavucontrol)$
windowrule = float on, center on, match:class ^(nm-connection-editor)$

# Transparencia + blur (efecto cristal como la demo ML4W)
windowrule = opacity 0.88 override 0.82 override, match:class ^(kitty)$
windowrule = opacity 0.93 override 0.88 override, match:class ^(Thunar)$
windowrule = opacity 0.95 override 0.90 override, match:class ^(firefox)$
